import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { ListToolsRequestSchema, type Tool } from '@modelcontextprotocol/sdk/types.js';
import {
  buildCoreRegistry,
  createToolRegistry,
  invokeTool,
  toolInputJsonSchema,
  toolInputShape,
  toolOutputJsonSchema,
  toolOutputShape,
  type ToolContext,
  type ToolJsonSchemaObject,
  type ToolSpec,
} from '@co/core';

/** Server identity advertised to MCP clients on initialize. */
const SERVER_NAME = 'co';
const SERVER_TITLE = 'co orchestration tools';
/** Kept in lockstep with packages/mcp/package.json `version`. */
const SERVER_VERSION = '0.0.0';

export interface ToolActivityEvent {
  readonly phase: 'start' | 'end';
  readonly tool: string;
}

export interface CoMcpServerOptions {
  /**
   * The tools to offer. Defaults to {@link buildCoreRegistry}().list() — the canonical
   * `co_*` tools. Phase D passes a role-scoped subset here; the exposed tool list is ALWAYS
   * exactly these specs (1:1 with the registry — nothing added, nothing dropped).
   */
  readonly tools?: readonly ToolSpec[];
  /**
   * Builds the {@link ToolContext} for an invocation. Injected so the server is testable headless
   * (a fixed context over a temp store) and so L7 can own live, per-session identity-injection.
   * The MOUNT supplies identity; a tool never invents who is calling (mcp-tools.md). The default
   * stdio entry ({@link defaultContextFactory}) resolves agent+project+mail from env/cwd.
   */
  contextFactory: () => ToolContext | Promise<ToolContext>;
  /**
   * Advertise structured output JSON schemas in `tools/list`. Core always validates tool outputs
   * through `invokeTool`; this flag only controls optional wire metadata for clients that support it.
   */
  readonly advertiseOutputSchema?: boolean;
  /** Optional host instrumentation for turn-boundary/liveness: reports tool calls as MCP activity. */
  readonly onToolActivity?: (event: ToolActivityEvent) => void;
}

/**
 * Build an MCP server that mounts core's tool registry onto the MCP protocol. THIN: it adds no
 * orchestration logic — every tool dispatches into `@co/core` via {@link invokeTool}, which is the
 * single I/O-validation + dispatch seam (the schemas are the single syntax source, Principle 5).
 * Transport-agnostic: this server is independent of how a live session is hosted (stdio now; the
 * L7 identity-injecting session-host SURFACE is real — see `LiveSessionHostImpl` in
 * live-session-host.ts — while binding it to a provider's live pty transport stays host-side wiring).
 *
 * For each offered {@link ToolSpec} it registers a tool carrying the spec's title, description and
 * its zod input schema (mounted via core's `toolInputShape`, so the adapter stays zod-free —
 * AC-L2-1), optional output-schema metadata, and a handler that builds a `ToolContext` via `contextFactory`
 * and returns the structured result both as `structuredContent` (typed) and as a JSON text block
 * (for clients that read `content`). Output validation stays in core's `invokeTool`, even when
 * `advertiseOutputSchema` is false for client compatibility. The list handler advertises compact
 * JSON-schema projections generated by core, while call validation continues through the SDK/core
 * zod schemas registered here.
 */
export function createCoMcpServer(opts: CoMcpServerOptions): McpServer {
  const tools = opts.tools ?? buildCoreRegistry().list();

  // A registry built from exactly the offered specs, so `invokeTool` dispatches by name with full
  // input/output validation. No tool-name switch lives here (that would be orchestration logic in
  // the adapter, AC-L2-1) — dispatch is entirely core's `invokeTool`.
  const registry = createToolRegistry();
  for (const spec of tools) registry.register(spec);

  const server = new McpServer({
    name: SERVER_NAME,
    title: SERVER_TITLE,
    version: SERVER_VERSION,
  });

  for (const spec of tools) {
    const config = {
      title: spec.title,
      description: spec.description,
      inputSchema: toolInputShape(spec),
      ...(opts.advertiseOutputSchema === true ? { outputSchema: toolOutputShape(spec) } : {}),
    };
    server.registerTool(spec.name, config, async (args: unknown) => {
      opts.onToolActivity?.({ phase: 'start', tool: spec.name });
      try {
        const ctx = await opts.contextFactory();
        const structured = await invokeTool(registry, ctx, spec.name, args);
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(structured) }],
          structuredContent: structured as Record<string, unknown>,
        };
      } finally {
        opts.onToolActivity?.({ phase: 'end', tool: spec.name });
      }
    });
  }

  server.server.setRequestHandler(ListToolsRequestSchema, () => ({
    tools: tools.map((spec): Tool => {
      const tool: Tool = {
        name: spec.name,
        description: spec.description,
        inputSchema: asMcpToolSchema(toolInputJsonSchema(spec)),
      };
      if (opts.advertiseOutputSchema === true) {
        tool.outputSchema = asMcpToolSchema(toolOutputJsonSchema(spec));
      }
      return tool;
    }),
  }));

  return server;
}

function asMcpToolSchema(schema: ToolJsonSchemaObject): Tool['inputSchema'] {
  return schema as Tool['inputSchema'];
}
